; Script generated by the Inno Setup Script Wizard

#define MyAppName "Stopwrdzv4.0"
#define MyAppVersion "4.0"
#define MyAppPublisher "Volunteers"
#define MyAppURL "https://github.com/TrustViking/Stopwrdz"
#define MyAppExeName "stopwrdz_v4.exe"

[Setup]
AppId={{160A49BA-E8C3-495D-99DB-C074FFE1A278}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion}
VersionInfoVersion=4.0.0.0
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DisableDirPage=no
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
LicenseFile=LICENSE.txt
InfoBeforeFile=befor_install.txt
PrivilegesRequired=lowest
OutputDir=setup_install
OutputBaseFilename=stopwrdzv4_setup
SetupIconFile=stopwrdz_.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "config.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "stopwrdz_.ico"; DestDir: "{app}"; Flags: ignoreversion
Source: "vocabs\*"; DestDir: "{app}\vocabs"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:ProgramOnTheWeb,{#MyAppName}}"; Filename: "{#MyAppURL}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#MyAppName}}"; Flags: nowait postinstall skipifsilent

[Registry]
Root: HKCU; Subkey: "Software\Classes\*\shell\RunStopwrdz"; ValueType: string; ValueName: ""; ValueData: "Title to Stopwrdz.4.0"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\*\shell\RunStopwrdz"; ValueType: string; ValueName: "Icon"; ValueData: "{app}\stopwrdz_.ico"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\*\shell\RunStopwrdz\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""; Flags: uninsdeletekey

[UninstallDelete]
Type: filesandordirs; Name: "{app}\*.*"
Type: dirifempty; Name: "{app}"

; End of script
